service: summaraize-backend

frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-dotenv-plugin
  - serverless-websockets-plugin

custom:
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: false
      seed: false
      docker: true
      noStart: true
    seed:
      domain:
        sources:
          - table: ${self:provider.environment.USERS_TABLE}
            sources: [./resources/dynamodb-seed/users.json]
          - table: ${self:provider.environment.PAPERS_TABLE}
            sources: [./resources/dynamodb-seed/papers.json]

  # WebSocket settings
  websocketApiName: paperProcessStatus
  websocketApiRouteSelectionExpression: $request.body.action

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-2'}
  environment:
    USERS_TABLE: ${env:UERS_TABLE, ''}
    PAPERS_TABLE: ${env:PAPERS_TABLE, ''}
    CONNECTIONS_TABLE: ${env:CONNECTIONS_TABLE, ''}
    PAPERS_BUCKET: ${env:PAPERS_BUCKET, ''}
    JWT_SECRET: ${env:JWT_SECRET, 'local-dev-secret'}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY, ''}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID, ''}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET, ''}
    NODE_ENV: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
            - execute-api:ManageConnections

          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PAPERS_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}/index/*"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PAPERS_TABLE}/index/*"
            - "arn:aws:execute-api:${self:provider.region}:*:*/@connections/*"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: "arn:aws:s3:::cse416summaraize/*"

functions:
  # Authentication Functions
  signUp:
    handler: src/functions/auth/signup.handler
    events:
      - http:
          path: /api/auth/signup
          method: post
          cors: true

  login:
    handler: src/functions/auth/login.handler
    events:
      - http:
          path: /api/auth/login
          method: post
          cors: true

  googleLogin:
    handler: src/functions/auth/google-auth.handler
    events:
      - http:
          path: /api/auth/google
          method: get
          cors: true

  refreshToken:
    handler: src/functions/auth/refresh-token.handler
    events:
      - http:
          path: /api/auth/refresh
          method: post
          cors: true

  # User Profile Functions
  changeUsername:
    handler: src/functions/auth/change-username.handler
    events:
      - http:
          path: /api/auth/modify/username
          method: post
          cors: true

  changePassword:
    handler: src/functions/auth/change-password.handler
    events:
      - http:
          path: /api/auth/modify/password
          method: post
          cors: true

  changeProfileImage:
    handler: src/functions/auth/change-profile-image.handler
    events:
      - http:
          path: /api/auth/modify/profileImage
          method: post
          cors: true

  logout:
    handler: src/functions/auth/logout.handler
    events:
      - http:
          path: /api/auth/logout
          method: post
          cors: true

  # Paper Upload Functions
  requestFileUpload:
    handler: src/functions/papers/upload-request.handler
    events:
      - http:
          path: /api/upload/request
          method: post
          cors: true

  confirmUpload:
    handler: src/functions/papers/confirm-upload.handler
    events:
      - http:
          path: /api/upload/confirm
          method: post
          cors: true

  # Paper Processing Functions
  processPaper:
    handler: src/functions/papers/process-paper.handler
    timeout: 300 # 5 minutes for processing
    events:
      - s3:
          bucket: ${self:provider.environment.PAPERS_BUCKET}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - suffix: .pdf

  # Paper Reading Functions
  getContentUrl:
    handler: src/functions/papers/get-content-url.handler
    events:
      - http:
          path: /api/papers/{paperId}/contentUrl
          method: get
          cors: true

  getPaperDetail:
    handler: src/functions/papers/get-paper-detail.handler
    events:
      - http:
          path: /api/papers/{paperId}/detail
          method: get
          cors: true

  # Library Functions
  loadLibrary:
    handler: src/functions/library/load-library.handler
    events:
      - http:
          path: /api/library/load
          method: post
          cors: true

  searchPaper:
    handler: src/functions/papers/search-paper.handler
    events:
      - http:
          path: /api/papers/search
          method: post
          cors: true

  # WebSocket Functions
  wsConnect:
    handler: src/websocket/connect.handler
    events:
      - websocket:
          route: $connect

  wsDisconnect:
    handler: src/websocket/disconnect.handler
    events:
      - websocket:
          route: $disconnect

  wsPaperProcessStatus:
    handler: src/websocket/paper-process-status.handler
    events:
      - websocket:
          route: paperProcessStatus

resources:
  Resources:
    # DynamoDB Tables
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:USERS_TABLE, ''}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    PapersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:PAPERS_TABLE, ''}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: paperId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: paperId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:CONNECTIONS_TABLE, ''}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
